### ISSUE TITLE
Query and command?

### ISSUE THREAD

**Issue by curgan78** [cribskip/esp8266_lgawhp#1]
Hi!
Is only a query working or can the heat pump be controlled?

**Comment by cribskip** [comment]
Hi,

Heat pump can be controlled and queried. I'll upload the current version in the evening.

**Comment by cribskip** [comment]
@curgan78  I've uploaded the current version of the code.

Please note the "settings" in the main ino file which control the compilation behaviour. I'm running the esp with an attached modbus energy meter and (currently) not with the PENKTH emulator but with some DS18B20 sensors.

Feel free if you have any questions. Sketch is running great
