### ISSUE TITLE
Emulator code

### ISSUE THREAD

**Issue by curgan78** [cribskip/esp8266_lgawhp#2]
The emulator also has an arduino code? 
I can't find it in the description.
How to connect the emulator?

**Comment by cribskip** [comment]
Yes, I didn't upload as the use of it is limited.
Got to the conclusion that the lg meter is not instructing the pump on how much power to use. 

The pump decides for itself based on the current parameters.

**Comment by cribskip** [comment]
Details of the registers are inside https://github.com/cribskip/esp8266_lgawhp/blob/master/PENKTH000.ino

and in the documentation. These registers are sufficient to tell the pump how much it is consuming but not enough to tell the energy (kWh) consumed.
